domain: gloo.bigbang.dev
credentials: ENC[AES256_GCM,data:9Q0A0M+21Z5kOhwx/GZhg9Sz+tOuz/tIA/7ssq5m4lYP8gqR1FcgOABNVM1jCqTS+OWrSBkauZHP+R7w7EZCfF9TjggWhMLswFYFUTnSJt1DCy4OhrMg/725ZfBoqMxVdWorLYvzKyvuW3LEyGv92EjKWRAJwC/P8e/gMtyravENfM/b830raxBBb88ypbWQmr3SxgU3LX5tlIi7RBiwj3JmyVucpbcKavRj/w6bHJi/X01uQ1c7cjCi5rqZ9C+17FQAx0cLVjBzID6JQBkHMO2Exc6plnb7KQ5FN0kiUoeUn2kyJVHXkJkwDeUrIaG2bDx5XHYI+/MbZegtvWjQ/Re3VqPN4cDkih/nIaw1o0o2YCfGeY2aJn/5c2xy+kBmB2vlYZ04salqKRQAvrwlhBYhaguiENcrU6qTLLE55xkcd+RiQAhiI2tv+W0QawKwuJBlV5P5HC50muiWWhD+GstriBkWSV2Ept15LUpObfcLkufIel5UH/CPi5dOs4HlIH1ACQ8JwBAgnxNEwa6251oVqP8KM1U9W5UEjoq77Ust+Kfnf/psYEYyNjVHxQvbOAl+ZWsojCZ7qKILuKryjD2dKD+mgSUXMgOvBFybPU2SCkqO1c9oxumGra5hZSOYNF48D7W4NNKgQUzcYVHsG2jTHgfcMEbcJCDn9mDuc3iesMfCVvtyeOnuOf0oGWjM5HsH4oSLpXSse9G0rMOkHfdYBqw2hjvFnyCIj9Q/0I6c9flI0iJlsWn72XbSO1ySTLW8/FmFMeuLYCvECtWH85sUsrwzpMNh1rDb1M9P8SOzUkhYtGLtIAYpZ1OTx2x7vqvM0ma4niDwzjRbnAKJShG9gSO715OVKV4nKhH6qJuD45Fb0M0RiqKvqZljUPbR2t/D57ArhHFHcxPXZC7bMG0WLLvBb4IxsdAfQl+6EeBhvbPYGo2pCkYjy9vZY1eQHxtYYqlqIw8jIpW3tmzsJM270zdt2gtMPbuMK1R9AAqFqVLugSazUCbWsZ/cLMUgWZWtfY5zMlMEzhYTHaRID+iefLjTTrE0SRvy06rAMEll34l+CqSGv+MOsj6ERNaHfE/qvk3wMZmpvTXq0Eai94/TA8EqV5ruSPLI2EvcMGsuT+mQgoVjHpmZhwpnIKDzmzWUDXu1g7oS3shokommLhXQGjhPPAenyAluZcbrl+D7qazoueitNaH9xIIIBld9Z2IC6RA6bsJOLOknuMIzx5nksjInPDxpdyXWduEOWm8wt59Tn8PCUxnX1r7CehtU5xbNnu6Ba0IdVZGjMB61Oi5PzNuoEsXfDp3e4B7VjBsShYawX4ctZ+5XHp/ViQlL6c3p0I18BOc48EqtqoLMqmX45fqjGsCdENdjel5z6tktsR17iRvwrdn5SwUON/lJZFl9RxKIcE8ymAung4U5iX9TF21ILCyyNEdJNmCV/hww9kejNEhqK+Qg7NEjhAZzvWqtQkwYfIAWXmzGXEFNO5+uXf/7l5woyVbi6ngGF2QFyap9t1AST+olMsAR/ZgPvHF5n/dCKruAkYMQ07p1zVgAFHP6Vq+mRoHqQdlgGa5EC9VYrftq1vQl69fviT4t3SXJd9YEjY5H3KDEQok3yhOlP9mfey4ofMCSV8jhsF0QDn4N8ruBj5k9YYHkpfFIVQ+0SHPI3OEVo2LCrtj8t/SUnm+MarGM/By36W5LqmLsCBxf9q0n/v4Eyafgc/Wm6SUOmbF4BqVaKb3bxVNUeDTXRpMX84MUfNJR29emetJNyC081cuVc96JSn/mtCIMorxy8bwqB5zxb3jnWyOzyM+F+gfZT58wwZkvYWUFu9cVN1fYGstg7bTMjWybclQNIAzJj8rG1N7Bse+vpl7bQDrZ+iUNkyMcQomj322/SBYmIMCdQH5OVw+FdDuODWxG8pqTjMgNIr4BCd37VE3aDjPPtcZ2J4nuU0QE/PPunmkFkW3xaQAakjkR/0ygQjAzyzYalLEwM6dQ8VSAwO5QOjRxP+VXRiYgm3vm9UFLOeWC3zhxvBq1Q9BD/7Qhor+tVp6ZhH5tj3L8jcakbgxqsAXPWm2jvJP/GFKBDrB5g6hUfd4h75Rf6WM85NJYcxHRv9G85yf6IJgb/v12uDwGlqU9XZ7ViznKgBdHXfIBI75Xj7Aj4aVwYfwb5knC09Fg87GBbTPyU9bblwUE2x/CSfzQ+JSYJdE8Z7zzynN3mxuptwjIL4THeonMhwKh8v258Fxp5KsohKDxWtS8OnkSBFjjuA1BbURQBj0nhfCvt++nD1h2jvP/hoX17HbYNj1KMu3gqJpYne+fw+ephHovQWq48JCZYobC60rar8KPi47n5X4t4P9GCij2U3uTm4ZSZgDNu1bLqVaKxwXxbxqi6zZ/t1ZvBnZFI4rIDjUKHAtu8lPAUZFhgPFGAk4y83SUpyJmkCICGM4Q3uxaez87h34FXgJrtQpc/5eDyg3jO6zCxiwaJqXsArhaj3KsaWWilEb4i6+apiI66HW/LJBJV2t+vgpJtP78+a4JExzM/9VCgHj/HTDYy4YShRLI+sWfZJpNG6mOkolcicak07Xk+gaQklVTmN+ewHxvWhxPt7VyRGu/pABJKTwI7cNhrcF43VIBKl2TGXmUSpT/n5JG/dyQUIy6Dy/E/hl9AJSriBv8sj+HR1m7f4WWQGg29ZcRE5BDvWKInEg2rU0hZoG11EiwRvksCBO92LMPJyh1K8tvBYcw6NkbCZdDFtqg1xt6A602YOi4bbg6nPzFBFGpiRxQ0ps6QqAuE1w6zmYRE08XH+uBMfzme23b2/qLdWtp9/jvQ/AV9PKK6iiOA0cN5F/SuaFXXB5GThaCy0YaD+Kw/8HeWZIhQvBR1qpmm9cKnZT1vLOe9hOHu1bZjjSP2e3oVtwY/Vrb8AOQnTtDO3zb51+YpoaMToUwsL4QUaFEiehyqAtaSEE5hTRkTCQlC5bVl7srYqZTrvZOw+pUeU3tAwxphc4L7kUtXnAsX3jZCi/pRnHBKz1l2TuN8Nwe5R2mahjC/2b4nAWFSS7m7JH1gwv8+sbUdTZVb4GBZTd43v1N3npjubL/J4r221hbtNbimTyebSAeukFTwnT3xYEARF0lOJj5HgHnc3K7ELOXniRx9BKjhDEAP6b+KsjJ2v1X//5YvEuzksuQXdZfqXuglyfdudxjypuYTNU7Zd28R4LbWrGnINXXU4fVgjrnbpf5M3daF7MOrteNl3GjgJLlMT3VpNgumTIo5r4KRM5o7ua5/JSsqHJc/7N74MNe7ZpIjdU3ep15qH2yAUaTLvHIpNhaByfR3tyXylHKwjZIoiVP4HRO7n3TmtYvY+IwZqaJarPbgkRCX9iIxTLRv38k7DZ17dCLwjr+YPAgw1CwHq3l946WfuiIEpNZDg0vaCNCYHONAvElk8awdRl/vxlc5v9qyO/kT+cgoWCF6QM8/rdnczLh7tSbFZmhzJPCUSKH/YINRq0AmoYnbgVXX1dKuygeOBBpDKdi1tQ3xQWaIYj4OcMZB5QEmR18miD31bgRQ8mcMLWgcUT/Ue3n4/dB+th18zruDEC2fHEeUMN4dasoutg3+VshtaGZNfri3bD/wDrotTnplcgvUa5ZniFieQhPwYgi8fZhv1+SFtE8hwMj2pcDi5nxr96StJ74D4XgYtsFKgtmXiptVB4E6SglvNgLmu5CmFbg/ClPgRhhISwmV0XqihWNWNY/yiUB7a1OQvQTFoZKtExWHphBwBkY7gMwT6BTP9loyI34BVGyIPqAFl3KaIKm8xCePB+8vaYwa9pScGDcVJSV0tCV3KEmbFOKWBHUNHDjE2bSRzuA2K5qJf4nnyZ/Q9vJk4SBRAkv0tx4ztKuCDBz+BFe2cIWKFDfPhT1MgnsI9sLrWBsqF9hBy/xCWmdNKzXCV8yrdVDDhf23xu8Ycfxh0l+Wlbrm3TNohZc+eWM9HAl0/cDk+P2SdZhTBFS7AP9dnzxVcpEUZF9Yuk1xwEgxriN5n5rjGuRQYnIGjoBl4AT0jRLPxH+HU8DbGLG+frwb4n1HAx11rBXsnr3kR9JHlNhFwQ9tURH16f/aFEheRtNRxlvmcHsEO7M/QYt7H25,iv:/ZxtBcA62+hUtlRggwv7JJluNP5V9l9PohDBVJpimAs=,tag:p88jcFXiiIYevTTRCGX81w==,type:str]
registryCredentials:
    - registry: registry1.dso.mil
      username: runyontr
      password: ENC[AES256_GCM,data:VDycrovdNNMq,iv:vXcJD3ZA8BtSOMjQ1mwZY2y09OwtlHsvI2gtOkMh++8=,tag:4544gIcZnVo35iZGY51V7A==,type:str]
    - registry: registry1.dsop.io
      username: runyontr
      password: ENC[AES256_GCM,data:cPTTws97PP+4,iv:0F2hCh2kgxspwUDycDCsulqskZ1lPbUIDsrwY8NW8qM=,tag:smwwFJEWD5hmz1CJ6BTrlg==,type:str]
    - registry: registry.gamewarden.io
      username: andrew.blanchard
      password: ENC[AES256_GCM,data:k5i5VE4bjudJZ7c=,iv:U0ybPgJJ0gpkFsvYGHdwvek7V160HKljmc32tjCDUx0=,tag:gkezSlbVA23O6/EhChh4NQ==,type:str]
    - registry: registry.dso.mil
      password: ENC[AES256_GCM,data:w8Ce2b16u0WHPBhDlhJcsJ2zsVEAnBxOCKOrJwBEAfwu,iv:v0CGerffQYiQ8gFKvPpl7oMvd5wNKkXNeqnjl0uOtwM=,tag:jzZkY5B7DVgp8GyJbJ0c/g==,type:str]
    - registry: code.il2.dso.mil
      password: ENC[AES256_GCM,data:i2rrogt2xR90M3VrekIM1gi0RY8=,iv:CGMRCca+Kv82RARk3CIKsYZaAfgwkNVYNphT1wYOQ5Y=,tag:/DQ7N+kNmW66I/9S2tqQ7w==,type:str]
gatekeeper:
    values:
        violations:
            allowedDockerRegistries:
                match:
                    excludedNamespaces:
                        - istio-system
                        - external-dns
                        - gloo-mesh
jaeger:
    enabled: false
twistlock:
    enabled: false
loki:
    enabled: true
promtail:
    enabled: true
eckoperator:
    enabled: false
logging:
    enabled: false
fluentbit:
    enabled: false
monitoring:
    enabled: true
    values:
        istio:
            enabled: true
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:950698127059:key/a2033cc0-fa97-41ea-9f33-d03266745335
          created_at: "2022-06-24T14:05:32Z"
          enc: AQICAHgBzAXGSUsBPPez012gkh0aDCM5Ggp5aDIfr3StC9gSQAE5OAnmbv6K6/ETE2vMcXPLAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMPh4nSKbtSaYGNN6LAgEQgDsoKr7GQgIxDDEGuPpA6cIojZ/2nwgv8eiZURtOb/U5H937Jd9Zo8+PzAbO3ERUMmbu9IprfO95WvmmPQ==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-06-24T14:05:33Z"
    mac: ENC[AES256_GCM,data:/ycwxLHYsYtHliVaWMzVWHVUFnlL5MOXhu1voHAXF7pwX2ovBSxEZ+b5gTSzbECN6wOxkHkO8QeX27u5bVp2qD17oQ2V22nMXhYhVPx+lqNj4VMirXHWX8SEAcT2dUjttobjQfSqPhi3CqDvJLrzIWGO1zhsAq1HTIVNUADC0EE=,iv:8yJcSi80xlW5w8yLs1aYZsrS/86T9/48uZBkWbgwESM=,tag:xrzyqAeFswIDWPz0TeC7cw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|credentials|password)$
    version: 3.7.3
